### ISSUE TITLE
solo key page has unreadable text

### ISSUE THREAD

**Issue by crun** [dicekeys/dicekeys-app-ios#127]
the solo key page has text that starts "apple prevents apps on iphones and ipads fro...". there's no way to scroll or resize this text so its content remains a mystery. also applies to the following sentence/paragraph.
device is iphone 12m running ios14.4
![IMG_2419](https://user-images.githubusercontent.com/1566124/110511669-4cc1b380-80b9-11eb-8652-b4806c085634.png)

**Comment by UppaJung** [comment]
Thanks for the screenshot to illustrate.  I'm on it.

**Comment by crun** [comment]
hi. updated the dicekeys app on 13mar. same issue only the fixed text is now scary red. still don't know what i need to do to use this product on my iphone ....
![IMG_2440](https://user-images.githubusercontent.com/1566124/111714133-3da3d980-880e-11eb-91a6-6d32fad55d68.PNG)

**Comment by crun** [comment]
if need be, i may be able to test this before you go through the nightmare of the apple approval process. let me know.

**Comment by UppaJung** [comment]
@crun, that would be awesome!

**Comment by crun** [comment]
i have testflight installed on my phone. just let me know when you've got something to test.
