### ISSUE TITLE
API Crashes on getSealingKey request

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-app-ios#132]
To reproduce, use this [API request link](https://dicekeys.app/?command=getSealingKey&requestId=1&respondTo=https%3A%2F%2Fapi.dicekeys.app%2F--derived-secret-api--%2F&recipe=%7B%22allow%22%3A%5B%7B%22host%22%3A%22api.dicekeys.app%22%7D%5D%7D&recipeMayBeModified=true) in the browser, which will open in the app.

**Comment by angelix** [comment]
Fixed in 37fceed798c7dca70daee75fd27a64ea0549d366
