### ISSUE TITLE
BIP39 template recipe

### ISSUE THREAD

**Issue by angelix** [dicekeys/dicekeys-app-ios#161]
I have created the following [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) template recipe.
```
DerivationRecipe(type: .Secret, name: "Mnemonic Code (BIP39)", recipe: """
{"purpose":"bip39"}
""")
```

I have also created two views `BIP39 (12 words)` & `BIP39 (24 words)`
The difference between the two is that in the 12 words version we only get the 16bytes of the secretBytes().

**Comment by angelix** [comment]
12 words mnemonic provide enough security for the bitcoin network. It's easier to store and to input into the wallets. Some users prefer it over the 24 words mnemonic. 
But since user's won't need to store the mnemonic somewhere, and can use the QR code to input the mnemonic we can stick with the 24 words for now.
Maybe in the future if requested by users we can use a similar recipe with `lengthInBytes: 16` to create the 12 words mnemonic.

"Mnemonic Code" is how the spec names it, but is not very user friendly. What about "Cryptocurrency wallet" as the name of the recipe?

**Comment by UppaJung** [comment]
How about:

```
DerivationRecipe(type: .Secret, name: "Cryptocurrency Wallet Seed", recipe: """{"purpose":"wallet"}""")
```

Then, `if (purpose === "wallet")`, apps should set the default output format to BIP39.
