### ISSUE TITLE
Create PEM keys

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-app-ios#33]
You can probably use GPG verbose mode to create a template byte array, then insert the private and public keys into the byte array, and base64 encode.
See https://crypto.stackexchange.com/questions/76433/assistance-with-parsing-pgp-private-key-blocks-secret-key-packet-0x6-and-secr

https://tools.ietf.org/html/rfc5915

https://tools.ietf.org/html/rfc5958

https://tools.ietf.org/html/rfc5280#section-4.1.2.7

**Comment by UppaJung** [comment]
Additional research notes:
  PEM read implementation to be found here:
    https://github.com/gpg/gnupg/blob/23f1fc766af0b8585e100cd75c4b571fe3dad831/dirmngr/dirmngr-client.c

**Comment by angelix** [comment]
Additional research notes:

https://cirw.in/gpg-decoder/

**Comment by ahaasler** [comment]
Hi, any progress on this feature?

**Comment by UppaJung** [comment]
@ahaasler  wrote:
> Hi, any progress on this feature?

WQe have some basic OpenPGP/OpenSSH formats for generating signing/authentications in the Windows/Linux electron app and, shortly, in a beta release of the web app (once we debug why web workers aren't working for the release version). We'll then get feedback on the UX and push into the iOS app.

**Comment by UppaJung** [comment]
@ahaasler .  You should now be able to try this out via https://staging.dicekeys.app/

![image](https://user-images.githubusercontent.com/8259431/157698911-e907d921-2ede-489c-8d6d-e9a235ad4af7.png)
