### ISSUE TITLE
Password.deriveFromSeed returning nil for custom url recipe

### ISSUE THREAD

**Issue by Abhityagi16** [dicekeys/dicekeys-app-ios#56]
``

**Comment by UppaJung** [comment]
Can you provide more context (e.g. the line you're debugging on where you see nil returned and inputs to the function)?

**Comment by Abhityagi16** [comment]
I tried generating password for https://exampl.com. This is the json passed to `Password.deriveFromSeed`: `"{\"allow\":[{\"host\":\"*.exampl.com\"}],\"lengthInChars\":0}"`. The method returns an empty string not nil.

**Comment by UppaJung** [comment]
Simple error, simple fix.
