### ISSUE TITLE
Clicking on UnlockDiceKey only works some of the time

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-app-ios#63]
This is based on my iPad.

To reproduce, load a diceKey and safe it so that it will appear on home screen.
Go back to home screen by locking the DiceKey.

Try clicking on it.  The animation shows that the button is pressed, but sometimes it triggers auth and sometimes nothing happens.

**Comment by Abhityagi16** [comment]
Does it happen on mac or iOS?

**Comment by UppaJung** [comment]
iOS

**Comment by Abhityagi16** [comment]
I clicked on unlock close to 30 times and it asked for authentication every single time. Not able to reproduce this.

**Comment by Abhityagi16** [comment]
@UppaJung Are you still able to reproduce this?

**Comment by UppaJung** [comment]
It happened again once today.  Then couldn't reproduce again.  Leaving open but low priority

**Comment by UppaJung** [comment]
@Abhityagi16, I have a hypothesis about this.  I think what may be happening is that my finger activates TouchId so quickly, that a touch is detected outside the TouchId window and deactivates it the instant it appears.

**Comment by UppaJung** [comment]
I think this may be that it only works if you click on text and not the icon

**Comment by angelix** [comment]
I think there is a _onTapGesture_ that consumes the event.
