### ISSUE TITLE
Make button colors consistent

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-app-ios#80]
Walk through UI and make all buttons that have rectangular backgrounds a common color that can be configured programmatically (presumably a color from the Color extensions).

Exception: previous/next/ << / <<   can stay current color. 

![image](https://user-images.githubusercontent.com/8259431/106526959-d1a13680-6529-11eb-9d7c-cb472adfd250.png)

**Comment by Abhityagi16** [comment]
Done
