### ISSUE TITLE
Make "Derive a Secret" color consistent with other footer options in iOS

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/dicekeys-app-ios#84]
My fix the make the entire icon open the menu introduced a color inconsistency.

![image](https://user-images.githubusercontent.com/8259431/106591891-28425b00-6592-11eb-9bfe-1e8a945a43b2.png)

**Comment by Abhityagi16** [comment]
Done

**Comment by UppaJung** [comment]
In which PR?

**Comment by Abhityagi16** [comment]
Sorry my bad, I thought this ticket was to make Backup this Key color consistent with the rest
