### ISSUE TITLE
RecipeBuilder screen bottom sheet is going out of screen

### ISSUE THREAD

**Issue by Abhityagi16** [dicekeys/dicekeys-app-ios#96]
<img width="374" alt="Screenshot 2021-02-08 at 5 12 15 PM" src="https://user-images.githubusercontent.com/2264311/107215185-fcf7ba00-6a30-11eb-8ac6-fad271e6849a.png">

**Comment by Abhityagi16** [comment]
Ignore the 0 in center. That is something I'm testing

**Comment by UppaJung** [comment]
Please check if this is fixed by #106
